environment:
    CCACHE_BASEDIR: $CIRRUS_WORKING_DIR

    # Enforce sequential JIT'ing of files for controlled memory usage.
    HILTI_JIT_SEQUENTIAL: 1

    # Images for macOS
    IMAGE_MACOS_BIG_SUR:  big-sur-base
    IMAGE_MACOS_CATALINA: catalina-base

    # Branches to use for spicy-plugin and spicy-analyzers tests.
    ZEEK_SPICY_BRANCH:      main
    ZEEK_ANALYZERS_BRANCH:  main

macos_catalina_task:
  osx_instance:
    image: $IMAGE_MACOS_CATALINA

  always:
    ccache_cache:
      folder: /tmp/ccache
      fingerprint_script: echo $CIRRUS_TASK_NAME-$CIRRUS_OS

  environment:
    CCACHE_DIR: /tmp/ccache
    CCACHE_COMPRESS: 1

  update_git_script:
    - git submodule update --recursive --init

  install_dependencies_script:
    - brew install llvm bison flex cmake ninja python@3.8 sphinx-doc doxygen ccache
    - pip3 install "btest>=0.66" sphinx_rtd_theme

  configure_script:
    - ./configure --generator=Ninja --with-bison=/usr/local/opt/bison --with-flex=/usr/local/opt/flex --enable-ccache --enable-werror --prefix=/opt/spicy
  build_script:
    - ninja -C build all check
  test_build_script:
    - make -C tests test
  packaging_script:
    - ninja -C build package

  packages_artifacts:
    path: build/spicy*.tar.gz
    type: application/gzip

macos_big_sur_task:
  osx_instance:
    image: $IMAGE_MACOS_BIG_SUR

  always:
    ccache_cache:
      folder: /tmp/ccache
      fingerprint_script: echo $CIRRUS_TASK_NAME-$CIRRUS_OS

  environment:
    CCACHE_DIR: /tmp/ccache
    CCACHE_COMPRESS: 1

  update_git_script:
    - git submodule update --recursive --init

  install_dependencies_script:
    - brew install bison flex cmake ninja python@3.8 sphinx-doc doxygen ccache
    - pip3 install btest sphinx_rtd_theme zkg

  configure_script:
    - ./configure --generator=Ninja --with-bison=/usr/local/opt/bison --with-flex=/usr/local/opt/flex --enable-ccache --enable-werror --prefix=/opt/spicy
  build_script:
    - ninja -C build all check
  test_build_script:
    - make -C tests test
  packaging_script:
    - ninja -C build package

  packages_artifacts:
    path: build/spicy*.tar.gz
    type: application/gzip

homebrew_catalina_task:
  skip: $CIRRUS_BRANCH != 'main' && $CIRRUS_TAG == ''

  osx_instance:
    image: $IMAGE_MACOS_CATALINA

  script:
    - brew tap zeek/zeek
    - brew install spicy --HEAD
    - brew test spicy

homebrew_big_sur_task:
  skip: $CIRRUS_BRANCH != 'main' && $CIRRUS_TAG == ''

  osx_instance:
    image: $IMAGE_MACOS_BIG_SUR

  script:
    - brew tap zeek/zeek
    - brew install spicy --HEAD
    - brew test spicy
