on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Upload Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: 'Wait for status checks'
        id: waitforstatuschecks
        uses: "WyriHaximus/github-action-wait-for-status@v1"
        with:
          ignoreActions: "Upload Release Assets"
          checkInterval: 60
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0 # Needed by `scripts/autogen-version`.
      - name: Prepare archive
        run: |
          ./scripts/make-tarball.sh
      # For now we let Github automatically create releases from tags.
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      - name: Fetch platform packages
        run: |
          ./scripts/store-release-artifacts --commit ${{ github.sha }}
      - name: Upload Release Assets
        id: upload-release-assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            spicy*.tar.gz
            binary_artifacts/spicy*.tar.gz
            binary_artifacts/spicy*.deb
            binary_artifacts/spicy*.rpm
