# NOTE: keep this action in sync with `docker-tags.yml`.

name: Publish Docker
on:
  push:
    branches:
      # Since this action pushes a `latest` image it is only active for the `main` branch.
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: "recursive"
    - name: Get Version
      id: version
      run: echo "::set-output name=RELEASE_VERSION::$(cat VERSION)"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ci/Dockerfile.dockerhub
        push: true
        build-args: "SPICY_ZKG_PROCESSES=1"
        tags: |
          zeekurity/spicy-dev:latest
          zeekurity/spicy-dev:${{ steps.version.outputs.RELEASE_VERSION }}
