# NOTE: keep this action in sync with `docker-tags.yml`.

name: Publish Docker
on:
  pull_request:
  push:
    branches: [main]
    tags:
      - 'v*'
      - '!v*-dev'
      - 'release'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_ARGS: "SPICY_ZKG_PROCESSES=1"
      TEST_TAG: spicy:latest
    steps:
    - uses: actions/checkout@master
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: "recursive"

    - name: Get Version
      id: version
      run: echo "::set-output name=RELEASE_VERSION::$(cat VERSION)"

    - name: Compute target tag
      id: target
      env:
        RELEASE_VERSION: ${{ steps.version.outputs.RELEASE_VERSION }}
      run: |
        # Translate the Github reference into a tag name.
        #
        # - `release` tag maps to `spicy:latest`
        # - `v*` tag (excluding `v*-dev` tags) maps to `spicy:RELEASE_VERSION`
        # - `main` branch maps to `spicy-dev:latest`
        #
        # Any other refs are not published below.
        if [ "${GITHUB_REF}" = "refs/tags/release" ]; then
          echo "::set-output name=tag::spicy:latest"
        elif [ "${GITHUB_REF}" = "refs/heads/main" ]; then
          echo "::set-output name=tag::spicy-dev:latest"
        elif [[ "${GITHUB_REF}" = refs/tags/v* ]] && [[ "${GITHUB_REF}" != refs/tags/v*-dev ]]; then
          echo "::set-output name=tag::spicy:${RELEASE_VERSION}"
        fi

    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ci/Dockerfile.dockerhub
        load: true
        build-args: ${{ env.BUILD_ARGS }}
        tags: ${{ env.TEST_TAG }}

    - name: Login to ECR
      # Do not publish from PRs.
      if: github.event.name == 'push'
      uses: docker/login-action@v1
      with:
        registry: public.ecr.aws
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Login to DockerHub
      # Do not publish from PRs.
      if: github.event.name == 'push'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push
      # Only publish if we did compute a tag.
      if: github.event_name == 'push' && steps.target.outputs.tag != ''
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ci/Dockerfile.dockerhub
        push: true
        build-args: ${{ env.BUILD_ARGS }}
        tags: |
          public.ecr.aws/zeek/${{ steps.target.outputs.tag }}
          docker.io/zeekurity/${{ steps.target.outputs.tag }}
